[tool.pytest.ini_options]
minversion = "6.0"
addopts = ["-ra", "--showlocals", "--strict-markers", "--strict-config", "--cov-branch"]
xfail_strict = true
testpaths = ["tests"]

[tool.pycln]
all = true
